### ISSUE TITLE
Plugin for using it via Aqueduct

### ISSUE THREAD

**Issue by LOG-TAG** [fosscom/objectdb#11]
Considering 100% approach to REST API I'm looking for possible ways to make 100% Dart serverside REST API+DB [Aqueduc](https://aqueduct.io/docs/db/connecting/)t+Objectdb would be a good combo for Dart enthusiasts!

**Comment by Gee5ive** [comment]
@LOG-TAG 
I don't have a whole lot of time on my hands for dart stuff as I am doing mostly golang on the server now, but if you want to create  a separate repo to create an integration layer for objectDB with aqueduct, I'd be willing to contribute, shouldn't take more than a weekend to get something working between two people. Let me know if you are interested.

**Comment by magillus** [comment]
I love this idea, specially when this could be used in development environment without need of postgresql. 
I think first there needs to be some generic API inside Aqueduct to allow objectdb or other DB integration.

**Comment by marioreggiori** [comment]
I’m closing this issue _for now_ because of inactivity.

@LOG-TAG we can always reopen it though!
