### ISSUE TITLE
Issues on adding to the database

### ISSUE THREAD

**Issue by MrUnfunny** [fosscom/objectdb#46]
Hi,
I am trying to download a file with dio and then adding the file's data to the database. Sometimes, it gets added to the database and other times it doesn't. Can you please tell me if it's something that I'm doing wrong or is it a fault from the library.

```  
await dio.download(attachment.url, path,
          onReceiveProgress: (receive, total) {
        progress = ((receive / total));
        progressDataCallBack(progress);
      }, cancelToken: cancelToken).whenComplete(
        () async => await LibraryDownloadsDB().add(
          {
            'id': attachment.id.toString(),
            'name': attachment.name,
            'path': path,
            'fileType': attachment.fileType
          },
        ),
      );
```
This is my downloading function with call to add data to database.
```
  add(Map item) async {
    final db = ObjectDB(await getPath());
    db.open();
    await db.insert(item);
    db.tidy();
    await db.close();
  }

```

This is the add method to insert the data into database.

**Comment by marioreggiori** [comment]
The database should only be opened once. Multiple concurrent instances could cause this behaviour.
